# Ethereum
ethereum:
  initial:
    ether: 1000000000000000
  geth:
    connPool:
      maxConnTotal: 100
      maxConnPerRoute: 100
      maxConnIdle: 50
      maxIdleTimeSeconds: 300 # IMPORTANT!!! Should be less than server.connection-timeout
      readTimeoutSeconds: 300
      connectionTimeoutSeconds: 30
    url: http://localhost:8501
  contract:
    address: "0xfbb3719fd53afe9bc0af9dfb3601429c7a058d78"
    owner:
      address: "0x515b0bd2f69b2f6106bbb21a6e66f84740adcae9"
      privateKey: 76376803091642704957644354574496388818985034477174475164229193213582287584295
      wallet:
        file: c:/DEVELOPING/Etherium/devnet/node1/keystore/UTC--2018-04-02T13-30-36.958062800Z--a5c233471f6dd13a2f98a54badcf21d85605649a
        password: pwdnode1;
    transactionManager:
        custom: false
        manageNonce: true
  admin:
    wallet: "0xfba2068908057b811a0a9623f072dd2f6455748a"
  cryptocurrency:
    initial-supply: 1000000000000
    address: "0xa411245be2139e5081e75580b4ce09234c510fc0"
    gas-price: 0
    gas-limit: 430000
  mint-coins:
    default-comment: "Coins were successfully minted."
  initial-transfer:
    comment: "Initial coins transfer."

contractOperation:
  exceptionTimeout: 30000
  threadpool:
    coreSize: 2000
    maxSize: 10000
    queueCapacity: 10000

web3j.scope: singleton
#web3j.scope: prototype
web3j.pollingIntervalMillisec: 2500