# Ethereum
ethereum:
  initial:
    ether: 1000000000000000
  geth:
    connPool:
      maxConnTotal: 100
      maxConnPerRoute: 100
      maxConnIdle: 50
      maxIdleTimeSeconds: 300 # IMPORTANT!!! Should be less than server.connection-timeout
      readTimeoutSeconds: 300
      connectionTimeoutSeconds: 30
    url: http://localhost:8501
  contract:
    address: "0xcBF84B89414498f6F1d2F14E4BcF68fB9a0d33CA"
    owner:
      privateKey: 78917374818337044569113600265904518667624904769081976474081495335171398564570
      wallet:
        file: c:/DEVELOPING/Etherium/devnet/node1/keystore/UTC--2018-04-02T13-30-36.958062800Z--a5c233471f6dd13a2f98a54badcf21d85605649a
        password: pwdnode1;
    transactionManager:
        custom: false
  admin:
    wallet: "0xfba2068908057b811a0a9623f072dd2f6455748a"
  cryptocurrency:
    initial-supply: 1000000000000
    address: "0xa411245be2139e5081e75580b4ce09234c510fc0"
    gas-price: 2
    gas-limit: 4300000
  mint-coins:
    default-comment: "Coins were successfully minted."
  initial-transfer:
    comment: "Initial coins transfer."

contractOperation:
  exceptionTimeout: 30000
  threadpool:
    coreSize: 20
    maxSize: 100
    queueCapacity: 10

web3j.scope: prototype
web3j.pollingIntervalMillisec: 2500